{
 "title": "Mongo Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mongo Process (Up/Down)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{cluster_role=\"mongod\"}"
    }
   ]
  },
  {
   "title": "API Circuit",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "circuit_breaker_state{job=\"api\", dependency=\"mongodb\"}",
     "legendFormat": "Circuit"
    }
   ]
  },
  {
   "title": "Worker Circuit",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "circuit_breaker_state{job=\"worker\", dependency=\"mongodb\"}",
     "legendFormat": "Circuit"
    }
   ]
  }
 ]
}