{
 "title": "RabbitMQ Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages (Ready)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "msg" } },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Messages (Unacked)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "msg" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages (Total)",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "msg" } },
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Throughput (msg/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "circuit_breaker_state{job=\"api\", dependency=\"rabbitmq\"}",
     "legendFormat": "API Circuit"
    },
    {
     "expr": "sum(rate(rabbitmq_global_messages_delivered_total[10s]))",
     "legendFormat": "Delivered"
    },
    {
     "expr": "sum(rate(rabbitmq_global_messages_received_total[10s]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(rabbitmq_global_messages_acknowledged_total[10s]))",
     "legendFormat": "Acknowledged"
    },
    {
     "expr": "sum(rate(rabbitmq_global_messages_dead_lettered_rejected_total{queue_type=\"rabbit_classic_queue\",dead_letter_strategy=\"at_most_once\"}[10s]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "RabbitMQ Process (Up/Down)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 16, "w": 8, "h": 8 },
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "connections" }
   ]
  },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 16, "w": 8, "h": 8 },
   "targets": [
    { "expr": "rabbitmq_channels", "legendFormat": "channels" }
   ]
  }
 ]
}